name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Lint
        run: echo Run lint
#        run: ./gradlew lintDebug
#
#      - name: Upload html test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run test
        run: echo Run test
#        run: ./gradlew test
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: unit_test_report
#          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [ unit-test ]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run espresso tests
        run: echo Run espresso tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: instrumentation_test_report
#          path: app/build/reports/androidTests/connected/

  static-code-analysis:
    needs: [ instrumentation-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: SonarCloud Scan
        run: ./gradlew sonar -D "sonar.organization=ynjadhav" -D "sonar.projectKey=ComposeLearning" -D "sonar.host.url=https://sonarcloud.io/" -D "sonar.login=e63a609507c0bd30f7c1562f2751cf591ef97ece"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



